import { StyleSheet, Platform } from "react-native";
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from "react-native-responsive-screen";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  headerContainer: {
    backgroundColor: "#27446F",
    paddingTop: Platform.OS === "ios" ? hp('5%') : hp('3%'),
    paddingBottom: hp('3%'),
    paddingHorizontal: wp('5%'),
    borderBottomLeftRadius: wp('15%'),
    borderBottomRightRadius: wp('15%'),
    height: Platform.OS === "ios" ? hp('15%') : hp('13%'),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    padding: wp('1%'),
  },
  headerText: {
    color: "#FFFFFF",
    fontSize: wp('5.5%'),
    fontWeight: "bold",
  },
  scrollContent: {
    flexGrow: 1,
    padding: wp('5%'),
  },
  content: {
    flex: 1,
    paddingBottom: hp('3%'),
  },
  formContainer: {
    marginTop: hp('2.5%'),
  },
  input: {
    height: hp('6%'),
    borderColor: "#ccc",
    borderWidth: wp('0.25%'),
    borderRadius: wp('1.25%'),
    paddingHorizontal: wp('2.5%'),
    marginBottom: hp('2%'),
    backgroundColor: "#ffffff",
    fontSize: wp('4%'),
  },
  specificInput: {
    fontSize: wp('4%'),
    height: hp('5%'),
    borderColor: "#ccc",
    borderWidth: wp('0.25%'),
    marginBottom: hp('1%'),
    paddingHorizontal: wp('2.5%'),
    backgroundColor: "#E9ECEF",
    color: "#838383",
  },
  pickerWrapper: {
    borderWidth: wp('0.25%'),
    borderColor: "#ccc",
    borderRadius: wp('1.5%'),
    marginBottom: hp('2%'),
    backgroundColor: "#fff",
    overflow: Platform.OS === "android" ? "hidden" : "visible",
    ...Platform.select({
      ios: {
        height: hp('5%'),
        justifyContent: "center",
        backgroundColor: "#fff",
      },
    }),
  },
  iosPicker: {
    ...Platform.select({
      ios: {
        height: hp('25%'),
        marginTop: hp('1%'),
        width: "100%",
        color: "#000000",
        backgroundColor: "#f9f9f9",
        borderWidth: wp('0.25%'),
        borderColor: "#ccc",
        borderRadius: wp('1.5%'),
        zIndex: 1000,
        position: "relative",
      },
    }),
  },
  androidPicker: {
    height: hp('6%'),
    width: "100%",
    color: "#000000",
  },
  pickerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: wp('2.5%'),
  },
  pickerText: {
    fontSize: wp('4%'),
    color: "#707073",
  },
  pickerDisplayContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: wp('2.5%'),
    height: hp('5%'),
  },
  pickerDisplayText: {
    fontSize: wp('4%'),
    color: "#000000",
  },
  pickerItem: {
    color: "#000000",
    fontSize: wp('5%'),
  },
  helpText: {
    color: "#27446F",
    marginBottom: hp('0.6%'),
  },
  helpLink: {
    color: "#27446F",
    marginBottom: hp('2%'),
    textDecorationLine: "underline",
  },
  datePickerButton: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: hp('6%'),
    borderColor: "#ccc",
    borderWidth: wp('0.25%'),
    borderRadius: wp('1.25%'),
    paddingHorizontal: wp('2.5%'),
    marginBottom: hp('2%'),
  },
  dateText: {
    color: "#000000",
    fontSize: wp('4%'),
  },
  submitButton: {
    alignSelf: "center",
    width: wp('50%'),
    backgroundColor: "#27446F",
    padding: wp('3.75%'),
    borderRadius: wp('2.5%'),
    alignItems: "center",
    marginTop: hp('2.5%'),
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: "#FFFFFF",
    fontSize: wp('4.5%'),
    fontWeight: "bold",
  },
  summaryText: {
    marginTop: hp('2.5%'),
    textAlign: "center",
    color: "#666",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContent: {
    backgroundColor: "white",
    padding: wp('5%'),
    borderRadius: wp('2.5%'),
    width: wp('80%'),
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: hp('1%'),
  },
  closeIcon: {
    padding: wp('1.25%'),
  },
  closeButton: {
    position: "absolute",
    right: wp('2.5%'),
    top: hp('1%'),
  },
  closeButtonText: {
    color: "#27446F",
    fontSize: wp('4%'),
  },
  warningText: {
    color: "#D97706",
    backgroundColor: "#FFF8E1",
    padding: wp('2.5%'),
    borderRadius: wp('1.5%'),
    marginVertical: hp('1%'),
    fontSize: wp('3.5%'),
    textAlign: "center",
  },
  errorText: {
    color: "#FF0000",
    fontSize: wp('3.5%'),
    marginTop: hp('0.6%'),
    marginBottom: hp('0.6%'),
    textAlign: "left",
  },
  modalImage: {
    width: wp('100%'),
    height: hp('25%'),
    resizeMode: "contain",
    marginVertical: hp('1%'),
  },
  confirmationText: {
    marginTop: hp('2.5%'),
    fontSize: wp('4%'),
    color: "black",
    textAlign: "center",
  },
  modalTitle: {
    fontSize: wp('5%'),
    fontWeight: "bold",
    marginBottom: hp('1%'),
    textAlign: "center",
  },
  modalButton: {
    backgroundColor: "#27446F",
    padding: wp('2.5%'),
    borderRadius: wp('2.5%'),
    alignItems: "center",
  },
  modalButtonText: {
    color: "white",
    fontSize: wp('4%'),
  },
  turnOffAutoPayText: {
    color: "blue",
    textAlign: "center",
    marginTop: hp('2.5%'),
    textDecorationLine: "underline",
  },
  modalText: {
    fontSize: wp('4%'),
    marginBottom: hp('2.5%'),
    textAlign: "center",
  },
  PaymentAmountField: {
    height: hp('5%'),
    borderColor: "#ccc",
    borderWidth: wp('0.25%'),
    marginBottom: hp('1%'),
    paddingHorizontal: wp('2.5%'),
    color: "black",
    borderRadius: wp('1.5%'),
    fontSize: wp('4%'),
  },
  testErrorButton: {
    backgroundColor: '#ff6b6b',
    padding: wp('3.75%'),
    borderRadius: wp('1.25%'),
    marginTop: hp('1%'),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: hp('0.25%') },
    shadowOpacity: 0.25,
    shadowRadius: wp('1%'),
    elevation: wp('1.25%'),
  },
  testErrorButtonText: {
    color: '#ffffff',
    fontSize: wp('4%'),
    fontWeight: 'bold',
  },
});
